### PR TITLE
Redesigned Button and Navbar component

### PR DESCRIPTION
**Pull request by loharganesh**
## Summary

Redesign UI

## Description for the changelog

• Added new package SASS
• Added new styles
• Added Button component
• Redesigned Navbar component

## A picture or screenshot regarding change
changescreenshot

## Checklist

- [x] Build and linting is passing.
- [x] This change is not breaking existing flow of a system.
- [ ] I have written test case for this change.
- [x] This change is tested from all aspects and scenarios.
- [ ] Implemented any new third-party library _(Which not existed before this change)_.

### CODE REVIEW

**Comment by PatilShreyas** [comment]
@loharganesh Change looks good. But I have the below queries:

- Register (to be a volunteer) button is missing from the navigation bar.
- The previous design of the app was such as Register and Login buttons were in a collapsible navbar. People were not able to find those options easily. So we kept the Register and Login button such as they'll be always shown in the front (obviously when not logged in only). Can we do something here as well?
- How Logout action button will look like?

**Comment by imPiyushrRajput** [comment]
@loharganesh  Can you please make sure that the login and register button should not  be in the menu we want it to display in front in the mobile view

**Comment by loharganesh** [comment]
Ok, i will come with something, where login and register buttons will be visible to user all the time if not logged in.

**Comment by loharganesh** [comment]
@PatilShreyas @imPiyushrRajput can we put logout button inside navigation ?

**Comment by PatilShreyas** [comment]
@loharganesh Closing this due to inactivity. Feel free to re-open!

**Pull request closed without merging**
